"""
Django settings for euro2024 project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7um95s-f=!9=qkw15b4wzp!ace!86vm8iv9p$8!1vn0+34s39d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django_registration',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'joc',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'euro2024.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'euro2024.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

if os.getenv('DOCKER_CONTAINER'):
    POSTGRES_HOST = 'db'
else:
    POSTGRES_HOST = '127.0.0.1'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'euro2024',
#         'USER': 'postgres',
#         'PASSWORD': 'postgres',
#         'HOST': POSTGRES_HOST,
#         'PORT': '5432',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'ca'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

if os.getenv('DJANGO_ENV') == 'prod':
    DEBUG = False
    ALLOWED_HOSTS = ['.disbarat.cat']
    # ...
else:
    DEBUG = True
    ALLOWED_HOSTS = []

# From 2 scoops of Django
from unipath import Path as UniPath
BASE_DIR = UniPath(__file__).ancestor(2)
# MEDIA_ROOT = BASE_DIR.child("media")
STATIC_ROOT = BASE_DIR.child("static")
STATICFILES_DIRS = (
    BASE_DIR.child("resources"),
)
LOCALE_PATHS = (
    BASE_DIR.child("languages"),
)

# # django-inspectional-registration
REGISTRATION_DEFAULT_FROM_EMAIL = 'El Joc de l\'Eurocopa 2024 <eljocdeleurocopa@gmail.com>'
# DEFAULT_FROM_EMAIL = '2016eurocopa@gmail.com'
# REGISTRATION_REGISTRATION_EMAIL = False
# REGISTRATION_ACTIVATION_EMAIL = False
# REGISTRATION_REJECTION_EMAIL = False
# LOGIN_REDIRECT_URL = '/'
# LOGIN_URL = '/registration/login'

EQUIPS_PER_GRUP = 4
NUM_GRUPS = 6
ID_ADMIN = 1

# http://django-registration-redux.readthedocs.io/en/latest/quickstart.html
ACCOUNT_ACTIVATION_DAYS = 7  # One-week activation window; you may, of course, use a different vlue
## REGISTRATION_AUTO_LOGIN = True  # Automatically log the user in.
## REGISTRATION_ADMINS = [('Xavier', 'xjaner@gmail.com')]
## LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/registration/login'
LOGOUT_REDIRECT_URL = '/registration/login'
##
## # EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
## # EMAIL_FILE_PATH = '/tmp/app-messages'  # change this to a proper location
## EMAIL_HOST = "172.18.0.1"
##
REGISTRATION_FORM = 'joc.forms.RegistrationFormComplete'
SEND_ACTIVATION_EMAIL = False
